--PRAGMA TABLE_info([PUBLISHER]);
-- PRAGMA TABLE_info([BOOK]);
PRAGMA TABLE_info([BOOK_AUTHORS]);
/*PRAGMA TABLE_info([LIBRARY_BRANCH]);
PRAGMA TABLE_info([BOOK_COPIES]);
PRAGMA TABLE_info([CARD]);
PRAGMA TABLE_info([BOOK_LENDING]);
*/