/* 5. Update rating of all movies directed by 'Steven Spielberg' to 5 */

UPDATE RATING
SET REV_STARS=5
WHERE MOV_ID IN (SELECT MOV_ID 
		FROM MOVIES
		WHERE DIR_ID IN (SELECT DIR_ID
				FROM DIRECTOR
				WHERE DIR_NAME = 'STEVEN SPIELBERG'));

SELECT * FROM RATING;