/* 3. List all actors who acted in a movie before 2000 and also in a movie after 2015 (use JOIN operation). */

	SELECT ACT_NAME, MOV_TITLE, MOV_YEAR
	FROM ACTOR A
	JOIN MOVIE_CAST C
	ON A.ACT_ID=C.ACT_ID
	JOIN MOVIES M
	ON C.MOV_ID=M.MOV_ID
	WHERE M.MOV_YEAR NOT BETWEEN 2000 AND 2015;

-- 	OR (the below query does not use JOIN)
	
/*	SELECT A.ACT_NAME, A.ACT_NAME, C.MOV_TITLE, C.MOV_YEAR
	FROM ACTOR A, MOVIE_CAST B, MOVIES C
	WHERE A.ACT_ID=B.ACT_ID
	AND B.MOV_ID=C.MOV_ID
	AND C.MOV_YEAR NOT BETWEEN 2000 AND 2015; */
